### ISSUE TITLE
UnboundLocalError: local variable 'side' referenced before assignment

### ISSUE THREAD

**Issue by crazcalm** [tkshill/DomiKnows#1]
I am not sure what I did and I am not sure how to reproduce it, but this is the stacktrace I got.

Enter answer here.1
Invalid answer format. Please try again.
Traceback (most recent call last):
  File "app.py", line 385, in <module>
    attempt = run()
  File "app.py", line 373, in run
    game.run()
  File "app.py", line 324, in run
    decision = player.decide_move(board)
  File "app.py", line 241, in decide_move
    if side not in ("left", "right"):
UnboundLocalError: local variable 'side' referenced before assignment

**Comment by tkshill** [comment]
It was a missing continue statement. I fixed it, but I should also add some tests for the user input to make sure it doesn't happen again.
