### ISSUE TITLE
Please remove the .idea file from source control

### ISSUE THREAD

**Issue by crazcalm** [tkshill/DomiKnows#4]
I went to look at the commit change you did for a recent issue that was closed (The one where you added a continue after the raised error) 071aa9fd5ac3899b52c21, and the commit log was filled with changes that you editor made to maintain itself. It made it difficult to find the actual changes to the project code.

On a similar note, it looks like you accidentally put the __pycache__ files in git. They are not as annoying, but those binary files will change every so often when you do things like run your tests. So you might want to remove those too.

**Comment by tkshill** [comment]
Got rid of the .idea file and the **pychache** stuff as well. Thanks for pointing that out.

**Comment by tkshill** [comment]
They're still in the repo but they should no longer be tracked.
